### ISSUE TITLE
这是为什么

### ISSUE THREAD

**Issue by Yizelove** [zerosoul/chinese-colors#18]
这是出什么错误了，要怎么解决
![Screenshot_20230330_134716_edit_469095493426036](https://user-images.githubusercontent.com/108044328/228741453-8035a0d8-7c54-40d3-a3a3-bafca6bc1606.jpg)

**Comment by Yizelove** [comment]
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.6.2
2 info using node@v16.17.1
3 timing npm:load:whichnode Completed in 4ms
4 timing config:load:defaults Completed in 6ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/root/chinese-colors/.npmrc Completed in 6ms
10 timing config:load:project Completed in 9ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 4ms
16 timing config:load Completed in 31ms
17 timing npm:load:configload Completed in 31ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 2ms
20 verbose title npm run start
21 verbose argv "run" "start"
22 timing npm:load:setTitle Completed in 4ms
23 timing config:load:flatten Completed in 11ms
24 timing npm:load:display Completed in 13ms
25 verbose logfile logs-max:10 dir:/root/.npm/_logs/2023-03-30T05_46_05_739Z-
26 verbose logfile /root/.npm/_logs/2023-03-30T05_46_05_739Z-debug-0.log
27 timing npm:load:logFile Completed in 37ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 97ms
31 silly logfile done cleaning log files
32 timing command:run Completed in 28ms
33 verbose stack Error: Missing script: "start"
33 verbose stack
33 verbose stack Did you mean one of these?
33 verbose stack     npm star # Mark your favorite packages
33 verbose stack     npm stars # View packages marked as favorites
33 verbose stack
33 verbose stack To see a list of scripts, run:
33 verbose stack   npm run
33 verbose stack     at RunScript.run (/usr/lib/node_modules/npm/lib/commands/run-script.js:102:13)
33 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:134:5)
34 verbose cwd /root/chinese-colors
35 verbose Linux 3.10.0-1127.el7.x86_64
36 verbose node v16.17.1
37 verbose npm  v9.6.2
38 error Missing script: "start"
38 error
38 error Did you mean one of these?
38 error     npm star # Mark your favorite packages
38 error     npm stars # View packages marked as favorites
38 error
38 error To see a list of scripts, run:
38 error   npm run
39 verbose exit 1
40 timing npm Completed in 205ms
41 verbose code 1
42 error A complete log of this run can be found in:
42 error     /root/.npm/_logs/2023-03-30T05_46_05_739Z-debug-0.log

报错Log内容
